import './module/sw-cms/elements/big-image-with-text';
import './module/sw-cms/blocks/text-image/big-image-with-text';
import './module/sw-cms/blocks/text-image/custom-hero-image-with-text';
import './module/sw-cms/blocks/text-image/my-image-text-reversed';
import './module/sw-cms/blocks/text-image/five-text-image-bubble';
import './module/sw-cms/blocks/text/text-collapse-teaser';
import './module/sw-cms/blocks/text/custom-text-teaser';
import './module/sw-cms/blocks/commerce/test-product-slider';
import './module/sw-cms/elements/test-product-slider';
